### ISSUE TITLE
Rails 6 support?

### ISSUE THREAD

**Issue by Kevin-Kawai** [russellquinn/casein#100]
Are there any plans for rails 6 support? I understand it's still in beta and won't be officially out for a while but was just wondering if it was on anyone's radar. I tried it out and it looks like the version of Authlogic being used needs to be updated to support some sort of interface change.

**Comment by russellquinn** [comment]
Hi Kevin, there's nothing "officially" being worked in. If you—or anyone—get something running, let me know! Russell.

**Comment by Kevin-Kawai** [comment]
Hi Russell,
I have a working fork that solves the authlogic issue (simply updating it) that I use for one of my projects. I was thinking it might be neat to support actiontext for the admin pages. If you don't mind I would definitely be up for giving rails 6 support a shot!
Kevin

**Comment by russellquinn** [comment]
Sounds great! If you do go ahead, then keep basic Rails 6 support and Action Text in separate PRs. Otherwise, thanks!

**Comment by Kevin-Kawai** [comment]
I keep getting an error with capybara when I try and setup the database tables for development. I'm using the command `rake db app:db:migrate app:db:test:prepare` to setup development. I keep getting the below error in my terminal.
```
kevins-MacBook-Pro:casein kevinkawai$ rake app:db:migrate app:db:test:prepare
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - log/capybara_exceptions.log
/Users/kevinkawai/src/open_source/casein_fresh/casein/spec/rails_test_app/config/environment.rb:7:in `<top (required)>'

Caused by:
Errno::ENOENT: No such file or directory @ rb_sysopen - log/capybara_exceptions.log
/Users/kevinkawai/src/open_source/casein_fresh/casein/spec/rails_test_app/config/environment.rb:7:in `<top (required)>'
Tasks: TOP => app:db:migrate => app:db:load_config => app:environment
(See full trace by running task with --trace)
```
Any idea what I could be doing wrong?

**Comment by russellquinn** [comment]
Do you get the error if you follow the Casein instructions word for word? Is it just an error from setting up the test database?

**Comment by Kevin-Kawai** [comment]
yup, it looks like something to do with how I have the rails environment setup. When I specified the environment I was able to get it to continue. 
`RAILS_ENV=test rake app:db:migrate app:db:test:prepare`

After solving this, rails told me that I can't inherit from `ActiveRecord::Migration` directly.
```
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CaseinCreateAdminUsers < ActiveRecord::Migration[4.2]
/Users/kevinkawai/src/open_source/casein-fresh/spec/rails_test_app/db/migrate/20141220224414_casein_create_admin_users.rb:3:in `<top (required)>'
```
Once I fixed this problem I was able to get the database setup and the specs to work. I have a loose feeling that it might have to do with the version of rails the dummy app uses but I'm not really familiar with how it's setup so I'll do some more research. Do you by chance have any guesses on why this happens?

**Comment by matedemorphy** [comment]
@Kevin-Kawai have you published the rails 6 supported branch?
