### ISSUE TITLE
Doesnt work with latest version of rails(4.2) and authlogic (3.4.3)

### ISSUE THREAD

**Issue by CyborTronik** [russellquinn/casein#32]
I did new project and just installed casein.
Seems there is a real minor change but is need to do this fix in casein as I understand.

Take a look at: https://github.com/binarylogic/authlogic/issues/432

**Comment by CyborTronik** [comment]
bundle update authlogic
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "authlogic":
  In Gemfile:
    casein (~> 5.1.0) ruby depends on
      authlogic (= 3.4.3) ruby

    authlogic (3.4.4)

**Comment by russellquinn** [comment]
Fixed in the upcoming Casein 5.1.1
