### ISSUE TITLE
Can't disable a casein_select

### ISSUE THREAD

**Issue by lbain** [russellquinn/casein#34]
I'd like to disable a select option in certain conditions. In the past I've successfully used `disabled: true` like this:
```
= casein_text_field f, f.object, :field, disabled: true
```

But the select doesn't seem to work.

```
= casein_select f, f.object, :field, {test: 1}, disabled: true
```
This results in a working select drop down.

Is it possible to disable a `casein_select` field? If so, how should I change my code to work properly?

**Comment by russellquinn** [comment]
Hey,

    casein_select form, obj, attribute, option_tags, options = {}

The options parameter is a hash, which can take standard Rails attributes and Casein attributes. (It passes any non-Casein attribute through to the underlying helper).

So, try putting your options as a hash, e.g.

    casein_select f, f.object, :field, {test: 1}, {disabled: true}
