### ISSUE TITLE
WYSIWYG support with image upload?

### ISSUE THREAD

**Issue by vernondegoede** [russellquinn/casein#35]
I've been using Casein for a while now, and really miss the WYSIWYG editor functionality for text fields. Also, a basic file uploader for the WYSIWYG editor would be great!

Are there any plans on implementing this functionality in the near future?

Cheers,
Vernon

**Comment by russellquinn** [comment]
Hey there,

The idea is to keep Casein as simple as possible. There are many WYSIWYG editors out there, not everyone will agree on which is best.

I tend to use bootstrap-wysihtml5-rails:
https://github.com/Nerian/bootstrap-wysihtml5-rails

It's very quick to set up: add the gem, reference the CSS and JS, add a class to your text field, then call the JS function.

**Comment by russellquinn** [comment]
And it looks great in Casein!

![screen shot 2015-01-07 at 8 04 45 am](https://cloud.githubusercontent.com/assets/116075/5648500/e5279868-9643-11e4-8186-5801aa52e783.png)
