### ISSUE TITLE
form-control class forgotten on new casein_form_elements

### ISSUE THREAD

**Issue by rmuzzi** [russellquinn/casein#37]
just upgraded to 5.1.1 and tried the new form_tag. The class "form-control" was forgotten I guess.

fix:
casein/app/helpers/casein/casein_helper.rb Line 290 should be:
        form.send(field_helper_method, attribute, strip_casein_options(options_hash_with_merged_classes(options, 'form-control')))

Or am I doing something wrong?

**Comment by russellquinn** [comment]
Fixed in 5.1.1.3
