### ISSUE TITLE
unable to add admin user 

### ISSUE THREAD

**Issue by sagarghai** [russellquinn/casein#38]
when i run this command
rake casein:users:create_admin email=sagar@gmail.com [password=sagar]
 i get this error

[Casein] Created new admin user with username 'admin' and password '5e9b600462df58475e44ac84f476dad2'
rake aborted!
Don't know how to build task '[password=sagar]'

how do i get my preffered password?? 
and how do i delete an existing admin ?? or edit the details

**Comment by russellquinn** [comment]
Hey,

The  [ ] just show it's optional, the correct format to specify your own password is:

   rake casein:users:create_admin email=sagar@gmail.com password=sagar

You can't just delete the admin via Rake, but you can delete all users with:

    rake casein:users:remove_all

But, once you've created the admin user, you can just log in to Casein via the browser, go to the Users section (top-right) and then edit the username or password. So, even if you've created a user with an auto-generated password, just jump to the browser, log in, and then fix up your credentials to what you want.
