### ISSUE TITLE
Creating Admin from GUI

### ISSUE THREAD

**Issue by sahilbabbar** [russellquinn/casein#39]
Is there any way to create an admin from the GUI(other than terminal) like in refinery cms? If a web-app is shipped with Casein how the user(without any computer knowledge) can create an admin easily?

**Comment by russellquinn** [comment]
Hey,

Nope, this is a developer's toolkit to quickly build up a basic CMS system, which can then be expanded as required. It'll never have a GUI interface for designing forms, etc.

Russell.

**Comment by sahilbabbar** [comment]
Is this to keep Casein lightweight and fully customizable by the developer?

**Comment by russellquinn** [comment]
Yep, it's just outside the scope for this project.
