### ISSUE TITLE
Casein plugins naming conventions

### ISSUE THREAD

**Issue by petrosp** [russellquinn/casein#41]
Hey guys,

I have been using Casein in my last couple of projects and have realized the need of a 'Pages' functionality to allow users create their own pages and present them in the frond end. I have developed such a structure and I am trying to put this together in a rails engine gem that could also be named after 'casein-pages'  or sorts.

I was wondering if there are any conventions on the naming and/or any guidelines on developing plugins specifically for Casein.

My respects...

**Comment by russellquinn** [comment]
Hey there,

There's no real convention right now, though Casein-Pages sound reasonable. Can't wait to see it!

Russell.
