### ISSUE TITLE
How does casein handle belongs_to and has_many relationships?

### ISSUE THREAD

**Issue by willseward** [russellquinn/casein#42]

**Comment by russellquinn** [comment]
The short answer is: it doesn't really.

The more involved answer: I use it for a lot of 0..n relationships though, but each time is kinda different. The most common is that one model's Show page will list all the has_manys at the bottom, right? For that, I generate the Casein scaffolding for the has_many model and use the --no-index option (this makes all the form partials, but not an index page and won't add it to the tab navigation). Then I can just show the table partial in the parent's show page.

So there are ways to have Casein save you time, but ultimately it needs some manual coding to get it how you want it. 

If you have suggestions for a useful and generic way for it to handle these relationships in a better way, then let me know. But, generally, Casein is a programmer's toolkit, giving you the CMS basics but still requiring you to set up your views and forms in code. This is what makes it different from other CMS systems, for better and worse.

**Comment by zachrnolan** [comment]
@russellquinn Do you have any example code on how to do this? I'm trying to add a render to the show page and it keeps giving me errors. It would be nice to see how this is done in the code. Thanks!
