### ISSUE TITLE
Error scrypt.rb:137: [BUG] Segmentation fault, CFUNC  :sc_calibrate (ruby 2.1.5p273)

### ISSUE THREAD

**Issue by maxivak** [russellquinn/casein#43]
I am trying to create a new user by the command:
    
    rake casein:users:create_admin

it gives an error:

    DL is deprecated, please use Fiddle
    D:/Ruby215/lib/ruby/gems/2.1.0/gems/scrypt-1.2.1/lib/scrypt.rb:137: [BUG] Segmentation fault
    ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]

    -- Control frame information -----------------------------------------------
    c:0037 p:0041 s:0161 e:000160 METHOD D:/Ruby215/lib/ruby/gems/2.1.0/gems/scrypt-1.2.1/lib/scrypt.rb:137
    c:0036 p:0046 s:0152 e:000150 METHOD D:/Ruby215/lib/ruby/gems/2.1.0/gems/scrypt-1.2.1/lib/scrypt.rb:111
    c:0035 p:0028 s:0147 e:000146 METHOD D:/Ruby215/lib/ruby/gems/2.1.0/gems/scrypt-1.2.1/lib/scrypt.rb:73
    c:0034 p:0132 s:0141 e:000140 METHOD D:/Ruby215/lib/ruby/gems/2.1.0/gems/scrypt-1.2.1/lib/scrypt.rb:220
    c:0033 p:0050 s:0134 e:000133 METHOD D:/Ruby215/lib/ruby/gems/2.1.0/gems/authlogic-3.4.4/lib/authlogic/crypto_providers/scrypt.rb:52
    c:0032 p:0098 s:0130 e:000127 METHOD D:/Ruby215/lib/ruby/gems/2.1.0/gems/authlogic-3.4.4/lib/authlogic/acts_as_authentic/password.rb:240 [FINISH]
    c:0031 p:---- s:0124 e:000123 CFUNC  :public_send

I am using Ruby 2.1.5 with Rails 4.2.0 on Windows.

Seems like it is the problem with authlogic gem..

any help?

**Comment by maxivak** [comment]
According to upgrading instructions for Authlogic 3.4.0 (https://github.com/binarylogic/authlogic), I modified the file '/app/models/casein/admin_user.rb':

    ..
    module Casein
      class AdminUser < ActiveRecord::Base

      
      #acts_as_authentic { |c|        c.validate_email_field = false }

       
       # new     
        acts_as_authentic do |c|
            c.validate_email_field = false

            c.crypto_provider = Authlogic::CryptoProviders::Sha512

        end

**Comment by russellquinn** [comment]
Thanks for the report. I just pushed 5.1.1.4 with this fix.

**Comment by kobessas** [comment]
I am experiencing the same issue.

I am using Ruby 2.1.5 with Rails 4.0.13 on Windows and Casein 5.1.1.5.
