### ISSUE TITLE
Fantastic!

### ISSUE THREAD

**Issue by Amnesthesia** [russellquinn/casein#47]
I'm sorry, this isn't a real issue so I'm sorry if the notification is bothersome, but I just had to leave feedback somewhere:

This is fantastic! I'm a bit disappointed I haven't heard much of CaseIn before, because this is literally the best CMS I've ever come across in any language. Minimalistic, and working **exactly** the way I'd want a CMS to work: Work with the resources _I_ want, not a preset and having to get into a ton of documentation to write a plugin to extend it. Make no assumptions, just let me get started immediately and present me with a "Here's all the fields for whatever resource you wanted to be able to edit".

When writing a site for a client, this is just **amazing**. No confusion, no settings you didn't ask for, nothing. Not WYSIWYG in What You See Is What You Get but exactly What You Design Is What You Get.

I've made portfolio websites in other CMS' like Refinery, Locomotive, and Comfortable Mexican Sofa; Wordpress and Joomla in PHP; and when I want to add a custom resource like Project, nothing has ever been as simple and straight forward as CaseIn with its generators and simple installation process. I showed it to a friend and it inspired him to get started learning Rails immediately. Less than 3 minutes and a functional back-end was all set up, and I could get started designing the views instead.

I rarely give feedback, and especially not posted as an issue on Github, but I just felt I **had** to show my appreciation for this somehow.

THANK you! This is truly fantastic.

**Comment by russellquinn** [comment]
Great, thank you!!
