### ISSUE TITLE
Most optimum way to extend Casein

### ISSUE THREAD

**Issue by petrosp** [russellquinn/casein#53]
Hey guys,

I picked up an ambitious task to create a `Pages` plugin for `casein` which I dropped and now picked up again; I have come up with some difficulties, but first things first:
I have created the engine:
- `rails plugin new casein_pages --full`
- I then add `s.add_depndency 'rails','~> 4.2.1'` and `s.add_dependency 'casein','~> 5.1.1'` to the `gemspec` file.
- I create my model `rails g model Page title:string body:text`
- I then try to create the `casein` CRUD scaffold by issuing:
  `rails g casein:scaffold Page title:string body:text` which fails epically with

```
[WARNING] Could not load generator "generators/casein/scaffold/scaffold_generator". Error: uninitialized constant Casein::CaseinHelper.
.../vendor/bundle/ruby/2.2.0/gems/casein-5.1.1.5/lib/generators/casein/scaffold/scaffold_generator.rb:4:in `<class:ScaffoldGenerator>'
.../vendor/bundle/ruby/2.2.0/gems/casein-5.1.1.5/lib/generators/casein/scaffold/scaffold_generator.rb:2:in `<module:Casein>'
.../vendor/bundle/ruby/2.2.0/gems/casein-5.1.1.5/lib/generators/casein/scaffold/scaffold_generator.rb:1:in `<top (required)>'
```

Now, this clearly implies an error in the loading path, but I tried to `require` or/and `include` casein in different parts of my engine with no luck.

The error doesn't seem to go away. 

Any suggestions or/and insights please?

**Comment by aeksco** [comment]
To include specific components of a dependency (a decorator or a generator, for example) in a Rails engine you'll probably want to follow a pattern similar to this:


```
# casein_pages_engine_root/lib/casein_pages/engine.rb

require 'casein'

module CaseinPages
  class Engine < Rails::Engine

    config.to_prepare do
      Dir.glob(Rails.root + "lib/generators/**/*.rb").each { |d| require_dependency(d) }
    end

  end
end
```

```config.to_prepare``` ( from [Configuring Rails Applications](http://guides.rubyonrails.org/configuring.html) )

> to_prepare: Run after the initializers are run for all Railties (including the application itself), but before eager loading and the middleware stack is built. More importantly, will run upon every request in development, but only once (during boot-up) in production and test.

Hope this helps!

**Comment by petrosp** [comment]
It helps a great deal, thanks for that! Provides context and brings the pieces closer each other...

I have been putting some more thought on the architecture of a generic casein plugin and concluded,at least for now, that a strategy similar to how the Casein itself is implemented would be among the wisest to follow: 
- Create the model structure (namespaced I guess) in the plugin
- This will be CRUD'd from the Casein backend GUI; luckily the GUI scaffold generator is already implemented by Casein, so the engine will only run this generator to the main_app; backend is now done
- Evidently the biggest challenge lies on the frond end. I guess that Russell has intentionally left this part out -- maintainance for a start -- so users use their own creativity to implement it.

Now getting to the specifics of the CaseinPages plugin, the routing implementation needs most of the attention as each of `Casein::Page` draws its own route, repopulated on runtime on every `after_save`. It orbits obviously around the DB and inherits some associated issues with ActiveRecord, more specifically with (absence in development) eager loading of the engine's models resulting to failure to populate the routes. A bit tricky to discover, but once done, it ends up covering the routing very decently. Now, I am only using this gem, [this guy built it](https://github.com/mwlang/flowmor_router); 

Concluding, have been experimenting with the engine the last couple of days, gathered the best segments and am currently shaping its TDD attitude. It's my first Engine...my baby... so bare with me before the first push.

Feedback on architecture is highly appreciated!
