### ISSUE TITLE
Relation "casein_admin_users" does not exist

### ISSUE THREAD

**Issue by jwnx** [russellquinn/casein#56]
I've deployed casein to heroku and installed Sendgrid successfully, but when I try to create an admin account, I get the following error:

    Running `rake casein:users:create_admin email=admin@admin.com password=admin` attached to terminal... up, run.1310
    PG::UndefinedTable: ERROR:  relation "casein_admin_users" does not exist
    LINE 5:                WHERE a.attrelid = '"casein_admin_users"'::re...
                                          ^
    :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                    FROM pg_attribute a LEFT JOIN pg_attrdef d
                      ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                   WHERE a.attrelid = '"casein_admin_users"'::regclass
                     AND a.attnum > 0 AND NOT a.attisdropped
                   ORDER BY a.attnum
    rake aborted!
    ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "casein_admin_users" does not exist
    LINE 5:                WHERE a.attrelid = '"casein_admin_users"'::re...
                                              ^
    :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                         pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                    FROM pg_attribute a LEFT JOIN pg_attrdef d
                      ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                   WHERE a.attrelid = '"casein_admin_users"'::regclass
                     AND a.attnum > 0 AND NOT a.attisdropped
                   ORDER BY a.attnum

    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `async_exec'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `block in exec_no_cache'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
    /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:592:in `exec_no_cache'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:584:in `execute_and_clear'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql_adapter.rb:733:in `column_definitions'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:186:in `columns'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/connection_adapters/schema_cache.rb:43:in `columns'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/attributes.rb:93:in `columns'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/attributes.rb:98:in `columns_hash'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/inheritance.rb:205:in `subclass_from_attributes?'
    /app/vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.1/lib/active_record/inheritance.rb:54:in `new'
    /app/vendor/bundle/ruby/2.0.0/gems/casein-5.1.1.5/lib/railties/tasks.rake:13:in `block (3 levels) in <top (required)>'

My Gemfile:

    source 'https://rubygems.org'

    gem 'rails', '4.2.1'    
    gem 'jquery-rails'
    gem 'turbolinks'
    gem 'jbuilder', '~> 2.0'
    gem 'sdoc', '~> 0.4.0', group: :doc    
    gem 'sass-rails', '~> 5.0'
    gem 'coffee-rails', '~> 4.1.0'
    gem 'uglifier', '>= 1.3.0'

    group :development, :test do
      gem 'byebug'
      gem 'web-console', '~> 2.0'
      gem 'spring'
      gem 'sqlite3'
    end

    group :production do
    	gem 'pg'
    	gem 'rails_12factor'
    end

    gem 'casein', '~>5.1.1'

I'm running Ruby 2.2.2 and Rails 4.2.1 on Arch Linux

**Comment by Ruekompa** [comment]
Have you tried to run the command without specifing the passwor option? The pw will then be generated for you.

**Comment by jwnx** [comment]
heroku run rake db:migrate

Solved the issue :)
