### ISSUE TITLE
bootstrap-sass dependency

### ISSUE THREAD

**Issue by allupaku** [russellquinn/casein#59]
The bootstrap sass dependency is now 3.3.3 now which is looking for an exact match, I faced version conflict when i am using version 3.3.5.1 in my project. I know it is a silly and small thing to correct , but won't it be good to have the dependency as >= 3.3.3 for bootstrap-sass ? or for any dependency version for that matter ?

This is with latest version of ruby - 2.2.1 and rails 4.2.1 bundler 1.10.5

**Comment by zeiv** [comment]
I think the dependency should be updated to TWBS's `bootstrap` gem.  It's the canonical source now.

**Comment by brchristian** [comment]
@zeiv Would you be up for submitting a PR? This should be easy enough to update.

**Comment by brchristian** [comment]
We have relaxed the `bootstrap-sass` dependency so that it no longer requires an exact match, so I'm going to close this issue. As for updating to the `bootstrap` gem, that would require migrating casein from Bootstrap 3 to Bootstrap 4, which would be a major project. PRs welcome, of course!
