### ISSUE TITLE
Casein Pronunciation and Activity

### ISSUE THREAD

**Issue by cdesch** [russellquinn/casein#61]
How do you pronounce Casein? is it "Case In" or like the [protein](https://en.wikipedia.org/wiki/Casein)

Also, is this project still being maintained? I don't see much activity.

**Comment by russellquinn** [comment]
Hey, yes, it's the name of the protein. It was originally a CMS developed for a digital agency I founded named Spoiled Milk, hence the dairy theme.

How you pronounce the name of the protein is up to you. I'm British and say "Case In".

**Comment by cdesch** [comment]
Thanks
