### ISSUE TITLE
while creating new controller via scaffolding array's are not created properly

### ISSUE THREAD

**Issue by 10zil** [russellquinn/casein#64]
module Casein
  class ArticlesController < Casein::CaseinController
  
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_filter :needs_admin, :except => [:action1, :action2]
    # before_filter :needs_admin_or_current_user, :only => [:action1, :action2]
  
    def index
      @casein_page_title = 'Articles'
  		@articles = Article.order(sort_order(:[name)).paginate :page => params[:page]
    end
  end
and VIEWS as well
<td><%= casein_table_cell_link article.[name, casein_article_path(article) %></td>
<th><%= casein_sort_link "[name", :[name %></th>

ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
~/tenworkspace/my_prod/casein$ rails -v
Rails 4.0.12

**Comment by russellquinn** [comment]
Don't include the square brackets. Just:

rails g casein:scaffold ModelName field:type, field:type
