### ISSUE TITLE
Scaffolding question

### ISSUE THREAD

**Issue by yumao5** [russellquinn/casein#65]
Hi 

With your demo pic, "View recipe" page has "Feed title", "Live preview", "Body". How do I generate Scaffolding like that, could you give me a hint?

thx

**Comment by russellquinn** [comment]
That's all custom stuff I wrote in Rails. The point being, Casein makes the basic scaffolding, but gives you full access to extend how you like using the full power of Rails. This isn't a plug and plug CMS, it's the very basics (authentication, users, stylesheets, routes, scaffolding, etc.).

**Comment by yumao5** [comment]
thx. Just want to confirm with you, since I check gem's option and didn't anything related. Do want to miss that part. I am building small web app with your gem. It would wonderful if they are default option(I am lazy, :)), thank for your work.
