### ISSUE TITLE
No edit action for users

### ISSUE THREAD

**Issue by casconed** [russellquinn/casein#68]
Clicking on a user in the Casein>Users admin takes me to `http://localhost:3000/casein/admin_users/1` and I get an error:

`The action '1' could not be found for Casein::AdminUsersController`

Running `rake routes` lists an action: `edit_casein_admin_user GET    /casein/admin_users/:id/edit(.:format)            casein/admin_users#edit`

**Comment by russellquinn** [comment]
I don't see any problem with this in the latest version. It'd be the show action, not edit:

    casein_admin_user GET    /casein/admin_users/:id(.:format)                 casein/admin_users#show

Is this running on a fresh install and empty project? Or adding to an existing project?

**Comment by casconed** [comment]
adding to an existing project.

**Comment by russellquinn** [comment]
Looks like you might have a problem with your routes. Install on an empty project (takes a couple of minutes) and compare routes files. You might have a conflict somewhere.
