### ISSUE TITLE
uninitialized constant Casein::VERSION in casein_helper

### ISSUE THREAD

**Issue by Eptis** [russellquinn/casein#69]
I previously was running Casein 5.0.0 and upgraded to 5.1.1 on rails 4.2.4. I now get the following message when accessing the admin:
`uninitialized constant Casein::VERSION`

```
def casein_get_full_version_string
      "v#{Casein::VERSION}"
end
```

Any way I can fix this?

**Comment by ilhanoguzhan** [comment]
Can you add casein.rb in initializers and put this code
`require 'casein/version'`
