### ISSUE TITLE
[calibration error] scrypt.rb:142:in `__sc_calibrate'

### ISSUE THREAD

**Issue by icanth** [russellquinn/casein#73]
Hello, when i running the command:

    rake casein:users:create_admin email=you@yourdomain.com password=your_password

it gives me a error:

	calibration error
	/Users/hui/.rvm/gems/ruby-2.2.1/gems/scrypt-1.2.1/lib/scrypt.rb:142:in `__sc_calibrate'
	/Users/hui/.rvm/gems/ruby-2.2.1/gems/scrypt-1.2.1/lib/scrypt.rb:111:in `calibrate'
	/Users/hui/.rvm/gems/ruby-2.2.1/gems/scrypt-1.2.1/lib/scrypt.rb:73:in `generate_salt'
	/Users/hui/.rvm/gems/ruby-2.2.1/gems/scrypt-1.2.1/lib/scrypt.rb:220:in `create'
	/Users/hui/.rvm/gems/ruby-2.2.1/gems/authlogic-3.4.4/lib/authlogic/crypto_providers/scrypt.rb:52:in `encrypt'
	/Users/hui/.rvm/gems/ruby-2.2.1/gems/authlogic-3.4.4/lib/authlogic/acts_as_authentic/password.rb:240:in `password='
	/Users/hui/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.5/lib/active_record/attribute_assignment.rb:54:in `public_send'

my env is: ruby 2.2.1，Rails 4.2.5, casein '~>5.1.1'

**Comment by russellquinn** [comment]
Hey, I just verified this and it works find with ruby 2.2.1, Rails 4.2.5, and latest Casein.

Looks like Scrypt is failing due to a configuration issue on your system. Are you using rbenv or similar? Haven't done rbenv rehash?

Going to close as it's not directly a Casein issue.
