### ISSUE TITLE
How can I generate admin users view

### ISSUE THREAD

**Issue by manishnagdewani96170** [russellquinn/casein#74]
How can I generate admin users view like we create in devise? IS there anyway?

Can anyone help me?

Thanks in advance.

**Comment by russellquinn** [comment]
An admin users view is created automatically. It's the Users option right up in the top-right corner. Is that what you were asking?

**Comment by manishnagdewani96170** [comment]
No,I am asking how can we customize admin user views as we do in devise?Is there any command to do this like in devise we have rails g devise:views?

**Comment by russellquinn** [comment]
The built-in user admin templates are inside Casein core. You can build new ones for the Casein::AdminUser model using the normal scaffolding commands.
