### ISSUE TITLE
Polymorphism

### ISSUE THREAD

**Issue by tamoyal** [russellquinn/casein#76]
Is polymorphism supported with the scaffolding? If so, examples would be great. If not, mark as a feature so me or someone else knows it is not supported and to add it in? A standard posts and photos with comments example should suffice.

**Comment by russellquinn** [comment]
It's not supported by the scaffold generator, but you can edit the resultant views to add it in. The usual way is to generate scaffolding for the parent and the children, then move the child partials inside the parent, etc.
