### ISSUE TITLE
Using Bootsy WYSIWYG with Casein

### ISSUE THREAD

**Issue by josephhays** [russellquinn/casein#77]
Heyo! I'm using Casein happily with my [https://github.com/josephhays/hear](app) and was hoping you could help me with using bootsy. I'm running rails 4 and the newest casein and I have included bootstrap in my app. Bootsy, if you don't know has it's own form helpers but also works with Simple Form builder by using `as: :bootsy` as you can see in my `pages#new` view. However using `<%= casein_text_area f, f.object, :content, as: :bootsy %>` in my `casein/pages#new` view doesn't work properly. Any thoughts?

**Comment by russellquinn** [comment]
I haven't tried this, but try looking at the generated HTML for the casein_text_area and noting the CSS classes used, then using the vanilla Bootsy form helper and adding those Casein CSS classes in manually to manage the style.

**Comment by josephhays** [comment]
Haha, this was all my fault and I forgot to `@import bootsy` in the casein/custom.js file. Loving casein!

**Comment by josephhays** [comment]
Just wanted to add, bootsy never worked for casein, but [https://github.com/spohlenz/tinymce-rails](TinyMCE-rails) worked perfectly! Users just have to remember to `//= require tinymce` in your assets/javascript/casein/custom.js file. Thought I'd post this here for anyone else looking for the answer.
