### ISSUE TITLE
how can I create an admin user in production env?

### ISSUE THREAD

**Issue by LanceGin** [russellquinn/casein#78]
In my production environment, I use 
```
rake casein:users:create_admin email=abc@def.com
```
but Casin create an admin user in my development.sql so that I can't login in mywebsite/casin

how can I create an admin user in production env?

**Comment by russellquinn** [comment]
The same as any for any Rake task. This isn't Casein specific.

`rake casein:users:create_admin email=abc@def.com RAILS_ENV=production`
