### ISSUE TITLE
Possibility to use mongo db

### ISSUE THREAD

**Issue by sunil-shrestha** [russellquinn/casein#82]
We are planning to adopt this CMS with mongoid. Wondering if it is possible already or plan to support it in future?

**Comment by russellquinn** [comment]
I haven't tried Mongoid with Casein, but in theory it should just work as it interacts with Rails, not the underlying data store. What problems are you running into?

**Comment by sunil-shrestha** [comment]
Apparently, I have not tried fully. But from the generator, I see that it creates a migration file which in case of mongoid would require the attributes to be defined within the model. So, i was wondering if there are any other factors to be considered if I decide to go with mongoid.

**Comment by russellquinn** [comment]
Right, migrations to model attributes would be one thing. Unless anyone else here has tried this, you might be the first. So, please do let us know what you find. Thanks!

**Comment by sunil-shrestha** [comment]
Sure, I will. Thanks

**Comment by sunil-shrestha** [comment]
After making quick try, i come to realise that the biggest block from the Authlogic gem which is used for authentication  in Casein CMS. Authlogic does not support Mongoid out of the box. So far, I found few suggestions to patch Authlogic but have not found any convincing solution to make Authlogic work with Mongoid. I would be happy to know if there is any way to solve this.
