### ISSUE TITLE
Casein 5.2 - AdminUserSessions#new

### ISSUE THREAD

**Issue by elliotyeo** [russellquinn/casein#86]
I had upgraded to 5.2 and had it working and now when I start up the rails server and head to 'http://localhost:3000/casein' I can't seem to get past this error in app/views/layouts/casein_auth.html.erb:8:in 

_undefined local variable or method `casein_config_auth_stylesheet_includes'_

That file seems to be in the gem which I didn't touch so I'm unsure how to troubleshoot this. Any pointers would be appreciated.

**Comment by russellquinn** [comment]
Ah, casein/config_helper.rb was updated in 5.2 and had two additional methods added to it. (`casein_config_auth_stylesheet_includes` and `casein_config_auth_javascript_includes`). You can manually copy them from the template file here: https://github.com/russellquinn/casein/blob/master/lib/generators/casein/install/templates/app/helpers/casein/config_helper.rb

Or you can run `rake casein:install` again after installing 5.2 and show the differences on modified files to see what you need to change.

**Comment by russellquinn** [comment]
I updated the README file with upgrade instructions. Thanks for raising this.

**Comment by russellquinn** [comment]
@elliotyeo Official advice is to run `rails g casein:install` again (and not update from the template file).

"You should run 'rails g casein:install' again to install the new files and, when you reach 'config_helper.rb' press 'd' to show differences and manually merge the changes."

**Comment by elliotyeo** [comment]
Ah perfect! This fixed things for me. Thanks @russellquinn!
