### ISSUE TITLE
Renaming the casein route

### ISSUE THREAD

**Issue by floreasy** [russellquinn/casein#91]
Hello Russell and thank you for your work, it helped me a lot to develop my app faster :).

I am just thinking about a thing, in my app, the url /casein is in fact the link to my backoffice and the / is the link to the project itslef. I would like to change this name "/casein" to my backoffice but I m a bit lost, how could I change this name ? 

Thanks a lot,

Greetings,

Flo

**Comment by russellquinn** [comment]
Hi, you can use /admin too.

Or you can just add your own in your routes.rb

match "/whatever" => redirect("/casein"), via: :get
