### ISSUE TITLE
Redirecting to localhost

### ISSUE THREAD

**Issue by mkunkel** [russellquinn/casein#93]
After upgrading to 5.2.0.0, I started seeing any redirects changing the host to 127.0.0.1:8080

I have my `default_url_options` set correctly, as well as `casein_config_hostname`. I have not been able to trace the cause. Have I missed a configuration option?

**Comment by russellquinn** [comment]
Nothing was intentionally changed to create this behavior. I haven't noticed this happening with any of my installs either.

Did you update other things at the same time? Rails? Your web server?

**Comment by mkunkel** [comment]
Rails was updated at the same time, to 5.1.1

**Comment by russellquinn** [comment]
I'm not sure, sorry I don't have anything useful to contribute. Let me know if you figure it out.

**Comment by mkunkel** [comment]
Closing this. I created a test endpoint that has confirmed that this is a Rails issue.

**Comment by russellquinn** [comment]
OK, thanks for the update!
