### ISSUE TITLE
Glyphicons not working

### ISSUE THREAD

**Issue by nmeynard** [russellquinn/casein#94]
Hi,

First I'd like to thank you for you nice job !

I'm trying your gem it seems great but glyphicons aren't working at all (looked for many tutos and nothing working).

I tried to import the woff woff2 and ttf files myself, same result, also tried to install glyphicons-rails gem, same issue, casein keeps getting 404 errors no matter how I include the files (of course I've put them in the path casein is looking for, in assets fonts bootstrap, but always same issue)...

Could you please have a look at this ?

Thank you !

**Comment by russellquinn** [comment]
Hi, glyphicons are working.

If they're not working for you, you'll need to provide more information. 

1. What are you trying to do? (Include code.)
2. What do you expect to happen?
3. What is actually happening?

Russell.
